@echo off
echo Creating Car Model...
call php artisan make:model Car -m
echo Creating Car Controller...
call php artisan make:controller CarController --resource
echo Creating Team Model...
call php artisan make:model Team -m
echo Creating Brand Model...
call php artisan make:model Brand -m
echo Creating Order Model...
call php artisan make:model Order -m
echo Creating Order Controller...
call php artisan make:controller OrderController
echo Creating OrderItem Model...
call php artisan make:model OrderItem -m
echo Creating Review Model...
call php artisan make:model Review -m
echo Creating Review Controller...
call php artisan make:controller ReviewController
echo Creating Checkout Controller...
call php artisan make:controller CheckoutController
echo Creating Admin Controller...
call php artisan make:controller AdminDashboardController
echo Creating Mail...
call php artisan make:mail OrderConfirmed
echo Done.
